### ISSUE TITLE
main picture

### ISSUE THREAD

**Issue by usaelectricalsystems** [vike27/usaelectricalsystems-temp#2]
Replace main picture

**Comment by vike27** [comment]
@usaelectricalsystems send me picture to replace with

**Comment by usaelectricalsystems** [comment]
We need this logo on the web site, with the picture

**Comment by vike27** [comment]
@usaelectricalsystems  WHere is the picture? I do not see it.

**Comment by vike27** [comment]
@usaelectricalsystems you did not paste the logo?

**Comment by usaelectricalsystems** [comment]
aqui esta el logo y main page picture

**Comment by vike27** [comment]
@usaelectricalsystems where? I don't see it.....

**Comment by usaelectricalsystems** [comment]
i resent on regular email
