### ISSUE TITLE
Re-edit

### ISSUE THREAD

**Issue by usaelectricalsystems** [vike27/usaelectricalsystems-temp#4]
I wrote in the services, then did second service, filled only first line on both and when i tried to go back and re-edit I cant see the edit tab and I cant write more in the service, also would be nice to separate services as commercial, residential industrial and other services, its all one big column now probably you can spread it in a wide page on few columns.

**Comment by vike27** [comment]
@usaelectricalsystems If you want to edit any service, make sure you are logged in. Then go to the service you want to edit. then in url add    `/edit`

It will take you to edit page. I will make a link for it also just in case.

**Comment by vike27** [comment]
fixed
